server:
  port: 9001
spring:
  application:
    name: sprint-boot-producer
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    virtual-host: /

    listener:
      type: simple
      simple:
        default-requeue-rejected: false










